[theme]
base="light"
primaryColor="#1E90FF"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f5f5"
textColor="#000000"
font="sans serif"

[server]
enableCORS = false
headless = true

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
